apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    team: abc
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 8080

#kubectl run demonginx --image=nginx --port=8080
