---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pythonapprc
  labels:
    app: pythonapp
spec:
  selector:
    app: pythonapp
  replicas: 1
  template:
    metadata: 
      name: pythonpod
      labels:
        app: pythonapp
    spec:
      containers:
        - name: pythoncontainer
          image: dockerhandson/python-app:1
          ports:
           - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: pythonappsvc
spec:
  type: NodePort
  selector:
    app: pythonapp
  ports:
    - port: 5000
      targetPort: 5000


